### ISSUE TITLE
Feature request:  Option to disable plugin notifactions that aren't relevant...

### ISSUE THREAD

**Issue by ripvega** [OllisGit/OctoPrint-PrintJobHistory#172]
For example, I'd like to know about plugins as they become available but I have no interest in Prusa. Currently, I can't just ignore this one, I think.

Nice work, BTW.

**Comment by OllisGit** [comment]
Hi @ripvega,

I am not exactly sure what mean. Because you can disable the check.
![image](https://user-images.githubusercontent.com/24205767/140232367-71ccd707-ed0e-4f64-b8aa-6db01f8a96a8.png)

So, after you installed your needed plugins you can disable the popup. If a new version of your installed plugins appears, OP informs you about that.

**Comment by ripvega** [comment]
Thank you for the reply.

As I don't use Prusa slicer, having the pop up asking me every time is
uneccessary. However, if other plugins do become available, I would want to
get a pop up about those. So, a 'don't ask me again' option about Prisa
slicer in my case, would be useful, while keeping the plugin check active
for other things as I would still like to know about other plugins though.

Does that make sense?

Thank you for making this.

Ash

**Comment by OllisGit** [comment]
fyi: In one of the last releases (maybe [V1.15.2](https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/tag/1.15.2)) I changed the behaviour. If the popup is disabled, it automatically "appears" after a new PJH-Version is installed.
