### ISSUE TITLE
Add PrusaSlicerThumbnails

### ISSUE THREAD

**Issue by OllisGit** [OllisGit/OctoPrint-PrintJobHistory#28]
https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails

**Comment by jneilliii** [comment]
If utilizing the metadata `thumbnail` property then whatever changes you do to make this work will also allow the UltimakerFormatPackage plugin to also be compatible.

**Comment by ikopytko** [comment]
I made an attempt to resolve this issue using @jneilliii propose to use metadata to find out thumb path, and it is kinda better than before but still contains some manual path-related operations because what other plugins are storing in metadata is path for tornado url handler, not path on the disk. 

That's mean if there exists any other plugin for thumbnails which is based on Ultimaker Format Package or PrusaSlicer Thumbnails thaen it will work without any futher modification.

**Comment by jneilliii** [comment]
You could also just check against the `thumbnail_src` attribute to determine which plugin data folder the image is stored in. Each of my plugins use that to identify which plugin the thumbnail was generated from.

**Comment by OllisGit** [comment]
hi,
the first version of ufp doesn't include the meata-data, that's the reason why it is based on absolut paths.

Thx, a lot for your pull request I appreciate it very much.
I will take a look in the next days.

**Comment by jneilliii** [comment]
I think it did include it but it was a different path, ie a sub attribute of refs.

**Comment by OllisGit** [comment]
Implemented since V1.1.0
