### ISSUE TITLE
Idea: Also show prints started from the printer.

### ISSUE THREAD

**Issue by tehZeno** [OllisGit/OctoPrint-PrintJobHistory#38]
I sometimes directly print stuff from my printer (um2+ext with thinker firmware).
Octoprint monitors this, and octoslack also is able to report progress on it.. however it is not shown in the history plugin. Probably because the plugin listens to an event that is never fired when manually starting..

Any ideas as to how this could be implemented?

**Comment by OllisGit** [comment]
hmm...maybe this is a bug, because I looked into the Octoslack-Implementation and I use the same Event-Listener.

Please provide (or take a look) the octoprint.logs, maybe an error occurs and that is the reason why the job is not captured...btw. in the plugin-settings you checked capture-flag, right?
