### ISSUE TITLE
[estimated_end_time] ignores day light saving time

### ISSUE THREAD

**Issue by Harryhar** [OllisGit/OctoPrint-PrintJobHistory#42]
Like the title says, the displayed estimated_end_time is not correct when day light saving time is enabled.

**Comment by OllisGit** [comment]
Hi @Harryhar ,
I think you are in the wrong repository, because the [estimated_end_time] is not captured in the history.

Please raise a new issue in https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues
Also with a sample about what you see (and where) and what you excpect.
Python version is also an imported information

But maybe it is releated this this exiting issue: https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/150
This is implemented and will be released in the next days.

Thx, in advance
Olli
