### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by masterdot** [OllisGit/OctoPrint-PrintJobHistory#81]
Hey there,

My plugin doesn't track the prints anymore. Is there a problem or is my installation in a bad state?

**Comment by OllisGit** [comment]
Hi @masterdot,
please provide the octoprint logs, maybe there is some error tracked.

**Comment by masterdot** [comment]
It seems it does work again... Maybe a one time error?!

**Comment by Enginecrafter77** [comment]
I experience the same issue. After the last update, PrintJobHistory doesn't log prints anymore. [Here](https://gist.github.com/Enginecrafter77/e3b6320505f79d67711203c9cbc3b90b) is the relevant octoprint.log data (filtered using `grep PrintJobHistory octoprint.log`).

The log says something about metafiles for the gcode files. I didn't study the codebase, but I blindly guess that the error might be that PrintJobHistory relies on uploading the gcode files through the website, but doesn't work for files uploaded through other means (for example FTP or SMB).

**Comment by masterdot** [comment]
OK, now it doesn't work again... Added the log with your plug-ins on debug.
P. S. Spool Manager doesn't fill the filament Infos...

**Comment by masterdot** [comment]
Here another log: https://www.dropbox.com/s/3dii3bbzvdzieqy/octoprint%20%282%29.log?dl=0

Spools are still not filled, but the last three prints did popup the history. Hope it does help a bit.

**Comment by OllisGit** [comment]
Hi @masterdot ,

the used length is captured from "FilamentManager-Plugin" and this is disabled in your case.
![image](https://user-images.githubusercontent.com/24205767/93663203-3e79cf80-fa66-11ea-9ed2-f041a51e3c86.png)

**Comment by OllisGit** [comment]
Hi @Enginecrafter77 ,

your case looks a little bit different, but I missed some informations in your look file:
![image](https://user-images.githubusercontent.com/24205767/93663277-fe671c80-fa66-11ea-99ab-5d289d5b2b34.png)
The error is mentioned in Line 259, but there is no addition error-message, like "Object is None".

Please provide a full octoprint log.

BR
Olli

**Comment by masterdot** [comment]
I have installed your spool manager and did disable the filament manager before I do delete it. So it seems to ignore your manager?

**Comment by OllisGit** [comment]
Currently there is no integration between PJH and SpoolManager, its on my List.
The filament-values were only picked up from FilamentManager

**Comment by masterdot** [comment]
Ahhhh... I thought it islready integrated because it's your plugin... That's the reason I did switch from filament manager to spool manager. To have the best integration bacause it's the same developer...

**Comment by Enginecrafter77** [comment]
Hi @OllisGit, sorry for the late reply.

As I said, the error was caused because the gcode file was uploaded using smb directly to the uploads directory, and hence not analyzed properly (i.e. no metadata file was created). This was also reported by FilamentManager plugin. As such, uploading through the web interface solved this problem.

If I were to encounter this problem again, I will open up a new issue dedicated to this. But at the time of writing, the problem I had is resolved and no other problems persist. PrintJobHistory works exactly as expected, though I no longer use in combination with DisplayLayerProgress (because of unrelated reasons).

And sorry for incorrectly identifying the problem on my side, and thus posting in an unrelated thread.

Have a nice day.
