### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by florianbeisel** [OllisGit/OctoPrint-PrintJobHistory#88]
[Slicer Settings Documentation](https://github.com/OllisGit/OctoPrint-PrintJobHistory/wiki/Slicer-Settings)  links to a GCODE template for Cura. But for versions prior 4.7.1 there exists a bug where having an equal sign will cause the Cura configuration to become corrupt. 

Ergo following the documentation with a version prior to 4.7.1. will result in a corrupt configuration. 

It would be smart to note that in the documentation to prevent unnecessary losses of the configuration (evenmore so because cura seems to have no fix for configuration anomalities other than delete everything)

See [Cura 4.7.1 Release Notes](https://github.com/Ultimaker/Cura/releases/tag/4.7.1)

**Comment by OllisGit** [comment]
Hi @florianbeisel,
thanks for reporting.

I am not sure what you mean, because I could not reproduce the issue:

- I installed CURA 4.7..1
- Added the linked gcode settings (https://gist.githubusercontent.com/tjjfvi/75210b2ed20ed194d6eab48bf70c4f12/raw/52c5ad77b0b71d9b9770e3b3cc260e738aada157/CuraSettingsInjector.gcode) to the Start-Section of my printer
- Sliced the model and save the file (without an error)
--> The file includes values from the template

Do you have a bug-report or something else?

**Comment by OllisGit** [comment]
No feedback -> closed!
